apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu:    200m
              memory: 512Mi
            limits:
              cpu:    1000m
              memory: 1Gi
