apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: ops-platform

patches:
  - path:   api-replicas.yaml
    target:
      kind: Deployment
      name: ops-api

commonLabels:
  environment: production

images:
  - name:    ops-platform/api
    newTag:  latest
  - name:    ops-platform/workflow-worker
    newTag:  latest
  - name:    ops-platform/memory-worker
    newTag:  latest
  - name:    ops-platform/recovery-worker
    newTag:  latest
  - name:    ops-platform/browser-worker
    newTag:  latest
