/**
 * R616 — Asset persistence: generated bytes → DO Spaces + metadata table + gallery.
 *
 * R609/R615 generate images. R610/R599 generate audio. R600 generates video.
 * Before R616, all those bytes sat as base64 blobs in novan_inbox.result jsonb
 * — never accessible as files, never reusable, growing the DB unbounded.
 *
 * R616 ships:
 *   - generated_assets table: id, workspace, business, kind, mime, bytes, prompt,
 *     source_brief_id, source_kind, s3_key, public_url, metadata jsonb, created_at
 *   - persistImageResult(): uploads PNG bytes to DO Spaces, writes asset row,
 *     returns the public URL. Strips base64 from the inbox result to keep the
 *     DB lean.
 *   - persistAudioResult, persistVideoResult: same shape for music/video.
 *   - list/get/recent ops + a /ops/gallery HTML route.
 *
 * Bucket layout:
 *   s3://novan-backups/assets/{workspace}/{kind}/{YYYY-MM-DD}/{id}.{ext}
 *
 * Reads are public (ACL=public-read) so the URL itself serves the asset — no
 * signed URL bookkeeping. Operator can drop the URL into a POD listing
 * directly. For private assets set ASSETS_PUBLIC=0 in env to use private ACL
 * + pre-signed URLs (future work).
 *
 * Falls back gracefully when offsite_s3 isn't configured: assets table still
 * records the row with public_url=null, base64 stays in the metadata jsonb
 * so the bytes aren't lost. Operator wires S3 → re-runs the gen, future
 * outputs hit the bucket.
 */
import { Buffer } from 'node:buffer'
import { createHash } from 'node:crypto'
import { sql } from 'drizzle-orm'
import { v7 as uuidv7 } from 'uuid'
import { db } from '../db/client.js'

async function ensureTable(): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS generated_assets (
      id              TEXT PRIMARY KEY,
      workspace_id    TEXT NOT NULL,
      business_id     TEXT,
      kind            TEXT NOT NULL,
      mime            TEXT,
      bytes           BIGINT,
      prompt          TEXT,
      source_brief_id TEXT,
      source_kind     TEXT,
      s3_key          TEXT,
      public_url      TEXT,
      sha256          TEXT,
      metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at      BIGINT NOT NULL
    )
  `).catch(() => {})
  await db.execute(sql`CREATE INDEX IF NOT EXISTS gen_assets_ws_kind_idx ON generated_assets (workspace_id, kind, created_at DESC)`).catch(() => {})
  await db.execute(sql`CREATE INDEX IF NOT EXISTS gen_assets_ws_biz_idx  ON generated_assets (workspace_id, business_id, created_at DESC) WHERE business_id IS NOT NULL`).catch(() => {})
  await db.execute(sql`CREATE INDEX IF NOT EXISTS gen_assets_sha_idx     ON generated_assets (workspace_id, sha256) WHERE sha256 IS NOT NULL`).catch(() => {})
}

// ─── S3 client (minimal AWS-sigv4 PUT) ───────────────────────────────────────
//
// We don't pull aws-sdk for one PUT call. Sigv4 in ~70 lines is fine.

interface S3Config {
  endpoint:   string         // https://nyc3.digitaloceanspaces.com
  region:     string         // nyc3
  bucket:     string
  accessKey:  string
  secretKey:  string
}

function s3Config(): S3Config | null {
  const endpoint  = process.env['NOVAN_OFFSITE_S3_ENDPOINT']
  const accessKey = process.env['NOVAN_OFFSITE_S3_ACCESS_KEY']
  const secretKey = process.env['NOVAN_OFFSITE_S3_SECRET_KEY']
  const bucket    = process.env['NOVAN_OFFSITE_S3_BUCKET']
  const region    = process.env['NOVAN_OFFSITE_S3_REGION'] ?? 'us-east-1'
  if (!endpoint || !accessKey || !secretKey || !bucket) return null
  return { endpoint, accessKey, secretKey, bucket, region }
}

function sha256Hex(buf: Buffer | string): string {
  return createHash('sha256').update(buf).digest('hex')
}

async function s3Put(cfg: S3Config, key: string, body: Buffer, contentType: string, opts: { public?: boolean } = {}): Promise<{ ok: boolean; status?: number; url?: string; error?: string }> {
  // R616 — minimal AWS Sigv4. Uses dynamic import for crypto.createHmac.
  const { createHmac } = await import('node:crypto')
  const hmacBuf = (key: Buffer | string, data: string): Buffer => createHmac('sha256', key).update(data).digest()

  const now = new Date()
  const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, '')   // YYYYMMDDTHHMMSSZ
  const dateStamp = amzDate.slice(0, 8)
  const host = new URL(cfg.endpoint).host
  const payloadHash = sha256Hex(body)
  const canonicalUri = `/${cfg.bucket}/${key.split('/').map(encodeURIComponent).join('/')}`
  const acl = opts.public !== false ? 'public-read' : 'private'

  const headers: Record<string, string> = {
    'host': host,
    'x-amz-content-sha256': payloadHash,
    'x-amz-date': amzDate,
    'x-amz-acl': acl,
    'content-type': contentType,
    'content-length': String(body.length),
  }
  const sortedHeaderKeys = Object.keys(headers).sort()
  const canonicalHeaders = sortedHeaderKeys.map(k => `${k}:${headers[k]!.trim()}`).join('\n') + '\n'
  const signedHeaders = sortedHeaderKeys.join(';')
  const canonicalRequest = `PUT\n${canonicalUri}\n\n${canonicalHeaders}\n${signedHeaders}\n${payloadHash}`
  const algorithm = 'AWS4-HMAC-SHA256'
  const credentialScope = `${dateStamp}/${cfg.region}/s3/aws4_request`
  const stringToSign = `${algorithm}\n${amzDate}\n${credentialScope}\n${sha256Hex(canonicalRequest)}`

  const kDate    = hmacBuf(`AWS4${cfg.secretKey}`, dateStamp)
  const kRegion  = hmacBuf(kDate, cfg.region)
  const kService = hmacBuf(kRegion, 's3')
  const kSigning = hmacBuf(kService, 'aws4_request')
  const signature = createHmac('sha256', kSigning).update(stringToSign).digest('hex')

  const authorization = `${algorithm} Credential=${cfg.accessKey}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`
  const url = `${cfg.endpoint.replace(/\/$/, '')}/${cfg.bucket}/${key}`

  try {
    const r = await fetch(url, {
      method: 'PUT',
      headers: { ...headers, Authorization: authorization },
      body: body as unknown as BodyInit,
      signal: AbortSignal.timeout(30_000),
    })
    if (!r.ok) {
      const text = await r.text().catch(() => '')
      return { ok: false, status: r.status, error: `s3 PUT ${r.status}: ${text.slice(0, 200)}` }
    }
    // DO Spaces public URL pattern
    const publicUrl = opts.public !== false
      ? `${cfg.endpoint.replace('https://', `https://${cfg.bucket}.`).replace(/\/$/, '')}/${key}`
      : url
    return { ok: true, status: r.status, url: publicUrl }
  } catch (e) { return { ok: false, error: (e as Error).message } }
}

// ─── Persist ─────────────────────────────────────────────────────────────────

export interface PersistInput {
  workspaceId:   string
  businessId?:   string
  kind:          'image' | 'audio' | 'video'
  bytes:         Buffer
  mime:          string
  prompt?:       string
  sourceBriefId?:string
  sourceKind?:   string
  metadata?:     Record<string, unknown>
}

export interface PersistResult {
  id:           string
  publicUrl:    string | null
  s3Key:        string | null
  bytes:        number
  sha256:       string
  storedInS3:   boolean
  reason?:      string
}

function extFor(mime: string): string {
  const m = mime.toLowerCase()
  if (m.includes('png'))  return 'png'
  if (m.includes('jpeg') || m.includes('jpg')) return 'jpg'
  if (m.includes('webp')) return 'webp'
  if (m.includes('mpeg') || m.includes('mp3')) return 'mp3'
  if (m.includes('wav'))  return 'wav'
  if (m.includes('flac')) return 'flac'
  if (m.includes('opus')) return 'opus'
  if (m.includes('mp4'))  return 'mp4'
  return 'bin'
}

export async function persistAsset(input: PersistInput): Promise<PersistResult> {
  await ensureTable()
  const id = uuidv7()
  const sha = sha256Hex(input.bytes)
  const ext = extFor(input.mime)
  const date = new Date()
  const dateStr = `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}-${String(date.getUTCDate()).padStart(2, '0')}`
  const key = `assets/${input.workspaceId}/${input.kind}/${dateStr}/${id}.${ext}`

  const cfg = s3Config()
  let publicUrl: string | null = null
  let storedInS3 = false
  let reason: string | undefined

  if (cfg) {
    const isPublic = process.env['ASSETS_PUBLIC'] !== '0'
    const r = await s3Put(cfg, key, input.bytes, input.mime, { public: isPublic })
    if (r.ok && r.url) { publicUrl = r.url; storedInS3 = true }
    else reason = r.error ?? `status ${r.status ?? 'unknown'}`
  } else {
    reason = 'NOVAN_OFFSITE_S3_* not configured — metadata only'
  }

  await db.execute(sql`
    INSERT INTO generated_assets (id, workspace_id, business_id, kind, mime, bytes, prompt, source_brief_id, source_kind, s3_key, public_url, sha256, metadata, created_at)
    VALUES (${id}, ${input.workspaceId}, ${input.businessId ?? null}, ${input.kind}, ${input.mime}, ${input.bytes.length},
            ${input.prompt ?? null}, ${input.sourceBriefId ?? null}, ${input.sourceKind ?? null},
            ${storedInS3 ? key : null}, ${publicUrl}, ${sha},
            ${JSON.stringify(input.metadata ?? {})}::jsonb, ${Date.now()})
  `).catch(() => {})

  return { id, publicUrl, s3Key: storedInS3 ? key : null, bytes: input.bytes.length, sha256: sha, storedInS3, ...(reason ? { reason } : {}) }
}

// ─── Reads ──────────────────────────────────────────────────────────────────

export interface AssetRow {
  id:           string
  workspaceId:  string
  businessId:   string | null
  kind:         string
  mime:         string | null
  bytes:        number | null
  prompt:       string | null
  sourceBriefId:string | null
  sourceKind:   string | null
  s3Key:        string | null
  publicUrl:    string | null
  sha256:       string | null
  metadata:     Record<string, unknown>
  createdAt:    number
}

function rowToAsset(r: any): AssetRow {
  return {
    id: r.id, workspaceId: r.workspace_id, businessId: r.business_id ?? null,
    kind: r.kind, mime: r.mime ?? null, bytes: r.bytes == null ? null : Number(r.bytes),
    prompt: r.prompt ?? null, sourceBriefId: r.source_brief_id ?? null, sourceKind: r.source_kind ?? null,
    s3Key: r.s3_key ?? null, publicUrl: r.public_url ?? null, sha256: r.sha256 ?? null,
    metadata: (r.metadata && typeof r.metadata === 'object') ? r.metadata : {},
    createdAt: Number(r.created_at),
  }
}

export async function listAssets(workspaceId: string, opts: { kind?: string; limit?: number; businessId?: string } = {}): Promise<AssetRow[]> {
  await ensureTable()
  const lim = Math.min(opts.limit ?? 50, 500)
  const r = opts.kind && opts.businessId
    ? await db.execute(sql`SELECT * FROM generated_assets WHERE workspace_id = ${workspaceId} AND kind = ${opts.kind} AND business_id = ${opts.businessId} ORDER BY created_at DESC LIMIT ${lim}`).catch(() => [] as unknown[])
    : opts.kind
    ? await db.execute(sql`SELECT * FROM generated_assets WHERE workspace_id = ${workspaceId} AND kind = ${opts.kind} ORDER BY created_at DESC LIMIT ${lim}`).catch(() => [] as unknown[])
    : opts.businessId
    ? await db.execute(sql`SELECT * FROM generated_assets WHERE workspace_id = ${workspaceId} AND business_id = ${opts.businessId} ORDER BY created_at DESC LIMIT ${lim}`).catch(() => [] as unknown[])
    : await db.execute(sql`SELECT * FROM generated_assets WHERE workspace_id = ${workspaceId} ORDER BY created_at DESC LIMIT ${lim}`).catch(() => [] as unknown[])
  return (r as any[]).map(rowToAsset)
}

export async function getAsset(workspaceId: string, id: string): Promise<AssetRow | null> {
  await ensureTable()
  const r = await db.execute(sql`SELECT * FROM generated_assets WHERE workspace_id = ${workspaceId} AND id = ${id} LIMIT 1`).catch(() => [] as unknown[])
  const row = (r as any[])[0]
  return row ? rowToAsset(row) : null
}

export async function stats(workspaceId: string): Promise<{ total: number; byKind: Record<string, number>; storedInS3: number; totalBytes: number }> {
  await ensureTable()
  const r = await db.execute(sql`
    SELECT kind,
           COUNT(*)::int AS n,
           COUNT(*) FILTER (WHERE public_url IS NOT NULL)::int AS in_s3,
           COALESCE(SUM(bytes), 0)::bigint AS total_bytes
    FROM generated_assets WHERE workspace_id = ${workspaceId} GROUP BY kind
  `).catch(() => [] as unknown[])
  const byKind: Record<string, number> = {}
  let total = 0, storedInS3 = 0, totalBytes = 0
  for (const row of r as Array<{ kind: string; n: number; in_s3: number; total_bytes: bigint | number }>) {
    byKind[row.kind] = Number(row.n)
    total += Number(row.n)
    storedInS3 += Number(row.in_s3)
    totalBytes += Number(row.total_bytes)
  }
  return { total, byKind, storedInS3, totalBytes }
}

// ─── HTML gallery ────────────────────────────────────────────────────────────

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export async function renderGallery(workspaceId: string, opts: { kind?: string; limit?: number } = {}): Promise<string> {
  const assets = await listAssets(workspaceId, { kind: opts.kind, limit: opts.limit ?? 60 })
  const st = await stats(workspaceId)
  const tiles = assets.map(a => {
    const visual = a.kind === 'image' && a.publicUrl
      ? `<img src="${escapeHtml(a.publicUrl)}" loading="lazy" alt="${escapeHtml((a.prompt ?? '').slice(0, 80))}" />`
      : a.kind === 'image'
      ? `<div class="placeholder">📷 ${a.bytes ?? 0}B (no S3)</div>`
      : a.kind === 'audio' && a.publicUrl
      ? `<audio controls preload="none" src="${escapeHtml(a.publicUrl)}"></audio>`
      : a.kind === 'video' && a.publicUrl
      ? `<video controls preload="metadata" src="${escapeHtml(a.publicUrl)}"></video>`
      : `<div class="placeholder">${a.kind} · ${a.bytes ?? 0}B</div>`
    const dl = a.publicUrl ? `<a href="${escapeHtml(a.publicUrl)}" download target="_blank" rel="noopener">⬇</a>` : ''
    const time = new Date(a.createdAt).toISOString().slice(0, 16).replace('T', ' ')
    return `
      <div class="tile">
        ${visual}
        <div class="meta">
          <div class="prompt" title="${escapeHtml(a.prompt ?? '')}">${escapeHtml((a.prompt ?? '(no prompt)').slice(0, 100))}</div>
          <div class="footer"><span>${time}</span> · <span>${a.kind}</span> ${dl}</div>
        </div>
      </div>`
  }).join('')
  return `<!doctype html><html><head>
<meta charset="utf-8"/><meta http-equiv="refresh" content="30"/>
<title>Novan Asset Gallery</title>
<style>
  :root { color-scheme: dark; --bg:#09090b; --card:#18181b; --border:#27272a; --fg:#fafafa; --mute:#a1a1aa; }
  body { background:var(--bg); color:var(--fg); font:14px -apple-system, system-ui, sans-serif; margin:0; padding:18px; }
  h1 { margin:0 0 4px; font-size:18px; }
  .sub { color:var(--mute); font-size:12px; margin-bottom:18px; }
  .filter { margin-bottom:18px; display:flex; gap:8px; }
  .filter a { color:#60a5fa; text-decoration:none; padding:4px 10px; background:#18181b; border:1px solid #27272a; border-radius:8px; font-size:12px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(220px,1fr)); gap:14px; }
  .tile { background:var(--card); border:1px solid var(--border); border-radius:10px; overflow:hidden; display:flex; flex-direction:column; }
  .tile img, .tile video { width:100%; aspect-ratio:1/1; object-fit:cover; display:block; background:#0f0f12; }
  .tile audio { width:100%; padding:8px; box-sizing:border-box; background:#0f0f12; }
  .placeholder { aspect-ratio:1/1; background:#0f0f12; color:var(--mute); display:flex; align-items:center; justify-content:center; font-size:11px; }
  .meta { padding:8px 10px; font-size:11px; }
  .prompt { color:var(--fg); margin-bottom:4px; line-height:1.3; overflow:hidden; text-overflow:ellipsis; }
  .footer { color:var(--mute); display:flex; gap:6px; justify-content:space-between; align-items:center; }
  .footer a { color:#60a5fa; text-decoration:none; }
  .empty { color:var(--mute); padding:40px; text-align:center; font-style:italic; }
</style>
</head><body>
<h1>Novan Asset Gallery · R616</h1>
<div class="sub">${st.total} total · ${st.storedInS3} in S3 · ${Math.round(st.totalBytes / 1024 / 1024 * 10) / 10} MB · refreshes every 30s</div>
<div class="filter">
  <a href="?token=any">all</a>
  <a href="?token=any&kind=image">images (${st.byKind['image'] ?? 0})</a>
  <a href="?token=any&kind=audio">audio (${st.byKind['audio'] ?? 0})</a>
  <a href="?token=any&kind=video">video (${st.byKind['video'] ?? 0})</a>
</div>
${assets.length === 0 ? '<div class="empty">No generated assets yet. Drop briefs via <code>inbox.bulk_image</code> to populate.</div>' : `<div class="grid">${tiles}</div>`}
</body></html>`
}
