/**
 * video-analyzer.ts — Drop-a-link video understanding.
 *
 * Operator pastes a video URL in chat (or sends via voice). This service:
 *   1. Detects the source (YouTube / Vimeo / direct mp4 / generic)
 *   2. Extracts metadata (title, duration, channel, thumbnail)
 *   3. Pulls transcript (YouTube has timed text; other sources fall back
 *      to a metadata-only analysis)
 *   4. Optionally: sends to Gemini for full video understanding (native
 *      YouTube URL support, no download needed)
 *   5. Returns structured analysis the chat brain injects into context
 *
 * Cost: $0 for metadata + transcript path. Gemini 2.0 Flash adds a few
 * cents per minute of video for full vision analysis when available.
 */

export interface VideoAnalysis {
  ok:              boolean
  url:             string
  source:          'youtube' | 'vimeo' | 'twitter' | 'tiktok' | 'direct' | 'unknown'
  title?:          string
  channel?:        string
  durationSec?:    number
  thumbnail?:      string
  publishedAt?:    string
  description?:    string
  transcript?:     string         // full transcript when available
  transcriptLang?: string
  summary?:        string         // generated by vision-capable LLM
  keyMoments?:     Array<{ atSec: number; label: string }>
  visualHighlights?: string[]      // descriptions of actual visual content seen
  framesAnalyzed?: number          // how many frames the brain looked at
  framesUrls?:     string[]        // urls of the frames seen (for audit)
  error?:          string
  fetchedAt:       number
}

/** Detect the source from the URL. Returns 'unknown' only if we truly can't tell — but playwright will still try. */
export function classifyVideoUrl(url: string): VideoAnalysis['source'] {
  if (!url) return 'unknown'
  if (/(?:youtube\.com|youtu\.be|youtube-nocookie\.com)/i.test(url)) return 'youtube'
  if (/(?:vimeo\.com|player\.vimeo\.com)/i.test(url))                return 'vimeo'
  if (/(?:twitter\.com|x\.com)\/.+\/(?:status|i\/web\/status|i\/broadcasts)/i.test(url)) return 'twitter'
  if (/(?:tiktok\.com|vm\.tiktok\.com)/i.test(url))                  return 'tiktok'
  if (/\.(?:mp4|mov|webm|m4v|mkv|avi|ogv)(\?|#|$)/i.test(url))       return 'direct'
  return 'unknown'
}

/** Even unknown URLs are tried — many sites have <video> embeds */
export function isLikelyVideoPage(url: string): boolean {
  if (classifyVideoUrl(url) !== 'unknown') return true
  // Heuristic patterns for general video sites
  return /(?:rumble|bitchute|odysee|peertube|loom|wistia|streamable|brightcove|jwplayer|video|watch|clip|reel|short)/i.test(url)
}

/** Extract the 11-char YouTube video id from any of the URL shapes. */
function youtubeVideoId(url: string): string | null {
  const patterns = [
    /[?&]v=([a-zA-Z0-9_-]{11})/,
    /youtu\.be\/([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/(?:embed|shorts|live)\/([a-zA-Z0-9_-]{11})/,
  ]
  for (const re of patterns) {
    const m = url.match(re)
    if (m) return m[1]!
  }
  return null
}

/** YouTube oEmbed — title, channel, thumbnail, no API key needed. */
async function fetchYouTubeOEmbed(url: string): Promise<{ title?: string; channel?: string; thumbnail?: string }> {
  try {
    const res = await fetch(`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(url)}`, {
      signal: AbortSignal.timeout(8000),
    })
    if (!res.ok) return {}
    const j = await res.json() as { title?: string; author_name?: string; thumbnail_url?: string }
    const out: { title?: string; channel?: string; thumbnail?: string } = {}
    if (j.title)         out.title     = j.title
    if (j.author_name)   out.channel   = j.author_name
    if (j.thumbnail_url) out.thumbnail = j.thumbnail_url
    return out
  } catch (e) {
    console.error('[video-analyzer] oEmbed fetch failed:', (e as Error).message)
    return {}
  }
}

/**
 * YouTube transcript via the page-scrape route. The reliable path:
 *   1. Fetch the watch page
 *   2. Extract `ytInitialPlayerResponse` JSON
 *   3. Find captionTracks → baseUrl
 *   4. Hit baseUrl with fmt=json3 to get timed text
 *
 * Returns empty when the video has no captions OR captions are disabled.
 */
async function fetchYouTubeTranscript(videoId: string): Promise<{ transcript?: string; lang?: string; description?: string; durationSec?: number }> {
  try {
    const pageRes = await fetch(`https://www.youtube.com/watch?v=${videoId}&hl=en`, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; Novan/1.0)', 'Accept-Language': 'en-US,en' },
      signal: AbortSignal.timeout(10_000),
    })
    if (!pageRes.ok) return {}
    // Cap response size — a malicious YouTube redirect could serve 100MB+
    // of unrelated HTML; we only need the initial-player-response JSON
    // which is always in the first ~2MB.
    const MAX_HTML_BYTES = 4 * 1024 * 1024
    const declared = Number(pageRes.headers.get('content-length') ?? 0)
    if (Number.isFinite(declared) && declared > MAX_HTML_BYTES) return {}
    const reader = pageRes.body?.getReader()
    let html: string
    if (!reader) {
      html = await pageRes.text()
      if (html.length > MAX_HTML_BYTES) html = html.slice(0, MAX_HTML_BYTES)
    } else {
      const decoder = new TextDecoder()
      let acc = ''
      let total = 0
      while (total < MAX_HTML_BYTES) {
        const { done, value } = await reader.read()
        if (done) break
        total += value.length
        acc += decoder.decode(value, { stream: true })
        if (total >= MAX_HTML_BYTES) { await reader.cancel().catch((e: Error) => { console.error('[video-analyzer]', e.message); return null }); break }
      }
      html = acc
    }

    // Extract ytInitialPlayerResponse — embedded as a JSON blob
    const m = html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;<\/script>/s) ?? html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s)
    if (!m) return {}
    const playerJson = JSON.parse(m[1]!) as {
      captions?:        { playerCaptionsTracklistRenderer?: { captionTracks?: Array<{ baseUrl: string; languageCode?: string; kind?: string }> } }
      videoDetails?:    { shortDescription?: string; lengthSeconds?: string }
    }

    const description = playerJson.videoDetails?.shortDescription?.slice(0, 2000)
    const durationSec = playerJson.videoDetails?.lengthSeconds ? Number(playerJson.videoDetails.lengthSeconds) : undefined

    const tracks = playerJson.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
    // Prefer English non-ASR, then English ASR, then first available
    const pick = tracks.find(t => t.languageCode === 'en' && !t.kind)
              ?? tracks.find(t => t.languageCode === 'en')
              ?? tracks[0]
    if (!pick) {
      const out: { description?: string; durationSec?: number } = {}
      if (description) out.description = description
      if (durationSec) out.durationSec = durationSec
      return out
    }

    const ttRes = await fetch(`${pick.baseUrl}&fmt=json3`, { signal: AbortSignal.timeout(10_000) })
    if (!ttRes.ok) {
      const out: { description?: string; durationSec?: number } = {}
      if (description) out.description = description
      if (durationSec) out.durationSec = durationSec
      return out
    }
    const text = await ttRes.text()
    const j = JSON.parse(text) as { events?: Array<{ segs?: Array<{ utf8?: string }> }> }
    const lines: string[] = []
    for (const ev of j.events ?? []) {
      for (const s of ev.segs ?? []) {
        if (s.utf8) lines.push(s.utf8)
      }
    }
    const transcript = lines.join('').replace(/\n+/g, ' ').replace(/\s+/g, ' ').trim()
    const out: { transcript?: string; lang?: string; description?: string; durationSec?: number } = {}
    if (transcript.length > 50) {
      out.transcript = transcript
      out.lang = `${pick.languageCode ?? 'en'}${pick.kind === 'asr' ? '-asr' : ''}`
    }
    if (description) out.description = description
    if (durationSec) out.durationSec = durationSec
    return out
  } catch (e) {
    console.error('[video-analyzer] transcript scrape failed:', (e as Error).message)
    return {}
  }
}

/**
 * Fetch frame images for a YouTube video. Two paths:
 *
 *   1. Always: the cover thumbnail in best available resolution
 *      (maxresdefault → hqdefault → mqdefault → 0). Real visual content.
 *
 *   2. When available: playwright-based screenshots of the video player
 *      at 25/50/75% of duration. This requires the playwright session
 *      service we already have + the YouTube embed URL (which loads
 *      without the consent cookie wall).
 *
 * `/1.jpg /2.jpg /3.jpg` are intentionally skipped — YouTube returns
 * 1-4KB placeholder images for those on most videos, not real frames.
 */
async function fetchYouTubeThumbnail(videoId: string): Promise<{ url: string; base64: string; mimeType: string; label: string } | null> {
  const thumbCandidates = [
    `https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`,
    `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    `https://i.ytimg.com/vi/${videoId}/mqdefault.jpg`,
    `https://i.ytimg.com/vi/${videoId}/0.jpg`,
  ]
  for (const url of thumbCandidates) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(8000) })
      if (!res.ok) continue
      const ab = await res.arrayBuffer()
      if (ab.byteLength < 3000) continue
      return {
        url, label: 'cover-thumbnail',
        base64: Buffer.from(ab).toString('base64'),
        mimeType: res.headers.get('content-type') ?? 'image/jpeg',
      }
    } catch { /* try next */ }
  }
  return null
}

/**
 * Generic playwright-based frame capture. Works on ANY page that
 * contains a <video> element. Handles:
 *   - YouTube (via embed URL — no consent wall)
 *   - Vimeo (via player.vimeo.com/video/ID)
 *   - TikTok, Twitter/X — direct page
 *   - Twitch clips, Reddit videos, Instagram reels (best-effort)
 *   - Direct .mp4 / .webm / .mov URLs — wrapped in a tiny HTML shell
 *
 * Strategy:
 *   1. Resolve page URL (embed form when known to bypass cookie walls)
 *   2. Navigate + wait for <video> element
 *   3. Read actual duration from the video element
 *   4. Seek to N fractions of duration + screenshot
 *
 * Returns whatever frames it could capture. Empty array on failure.
 */
async function captureVideoFramesViaPlaywright(
  source: VideoAnalysis['source'],
  url: string,
  videoId: string | null,
  hintDurationSec?: number,
): Promise<{ frames: Array<{ url: string; base64: string; mimeType: string; label: string }>; durationSec?: number }> {
  const frames: Array<{ url: string; base64: string; mimeType: string; label: string }> = []
  let durationSec: number | undefined = hintDurationSec

  // Resolve to a player-friendly URL
  let playerUrl = url
  if (source === 'youtube' && videoId) {
    playerUrl = `https://www.youtube.com/embed/${videoId}?autoplay=1&mute=1`
  } else if (source === 'vimeo') {
    // Vimeo IDs look like https://vimeo.com/123456789 → player.vimeo.com/video/123456789
    const m = url.match(/vimeo\.com\/(?:video\/)?(\d+)/)
    if (m) playerUrl = `https://player.vimeo.com/video/${m[1]}?autoplay=1&muted=1`
  } else if (source === 'direct') {
    // Wrap in a tiny HTML page so playwright can play it via a <video> tag
    const escaped = url.replace(/"/g, '&quot;')
    playerUrl = `data:text/html;charset=utf-8,${encodeURIComponent(`<!doctype html><html><head><style>body{margin:0;background:#000}video{width:100vw;height:100vh;object-fit:contain}</style></head><body><video src="${escaped}" autoplay muted controls></video></body></html>`)}`
  }
  // For tiktok/twitter/unknown: navigate the original URL and find <video>

  let mod: typeof import('playwright')
  try {
    mod = (await import('playwright' as string)) as typeof import('playwright')
  } catch {
    return { frames }
  }
  let browser: import('playwright').Browser | null = null
  let context: import('playwright').BrowserContext | null = null
  try {
    browser = await mod.chromium.launch({
      headless: true,
      args: ['--no-sandbox', '--autoplay-policy=no-user-gesture-required', '--disable-blink-features=AutomationControlled'],
    })
    context = await browser.newContext({
      viewport: { width: 1920, height: 1080 },     // 1080p capture for vision LLM clarity
      deviceScaleFactor: 1,
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36',
    })
    const page = await context.newPage()
    await page.goto(playerUrl, { waitUntil: 'domcontentloaded', timeout: 20_000 })

    // Wait for ANY video element. Some pages (TikTok, Instagram) lazy-load.
    await page.waitForSelector('video', { timeout: 15_000 })

    // Trigger play, then poll from the Node side for duration. Polling
    // from Node avoids missed-event races (loadedmetadata may fire before
    // a listener attaches inside page.evaluate, especially for data: URLs).
    const triggerPlay = async () => {
      try {
        await page.evaluate(() => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const doc = (globalThis as any).document as { querySelectorAll(s: string): unknown[] } | undefined
          if (!doc) return
          const list = Array.from(doc.querySelectorAll('video')) as Array<{
            currentSrc: string; videoWidth: number; videoHeight: number
            play(): Promise<void>; muted: boolean
          }>
          list.sort((a, b) => (b.videoWidth * b.videoHeight) - (a.videoWidth * a.videoHeight))
          const v = list.find(x => x.currentSrc || x.videoWidth > 0) ?? list[0]
          if (!v) return
          try { v.muted = true; void v.play() } catch { /* */ }
        })
      } catch { /* */ }
    }
    await triggerPlay()

    // Poll up to 8s for duration to settle
    let probe: { ok: boolean; duration: number; w?: number; h?: number; readyState?: number } = { ok: false, duration: 0 }
    const probeStart = Date.now()
    while (Date.now() - probeStart < 8000) {
      try {
        probe = await page.evaluate(() => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const doc = (globalThis as any).document as { querySelectorAll(s: string): unknown[] } | undefined
          if (!doc) return { ok: false, duration: 0 }
          const list = Array.from(doc.querySelectorAll('video')) as Array<{
            duration: number; currentSrc: string; videoWidth: number; videoHeight: number; readyState: number
          }>
          list.sort((a, b) => (b.videoWidth * b.videoHeight) - (a.videoWidth * a.videoHeight))
          const v = list.find(x => x.currentSrc || x.videoWidth > 0) ?? list[0]
          if (!v) return { ok: false, duration: 0 }
          return {
            ok: true,
            duration: Number(v.duration) || 0,
            w: v.videoWidth, h: v.videoHeight,
            readyState: v.readyState,
          }
        })
      } catch { /* */ }
      if (probe.ok && Number.isFinite(probe.duration) && probe.duration > 0) break
      // also break early if we have any video at all + been waiting >2s (some streams have no duration)
      if (probe.ok && probe.readyState && probe.readyState >= 2 && Date.now() - probeStart > 2500) break
      await page.waitForTimeout(400)
    }

    if (!probe.ok) return { frames }
    if (probe.duration && probe.duration > 0 && Number.isFinite(probe.duration)) {
      durationSec = probe.duration
    }

    // Decide where to seek — denser sampling = better vision understanding
    const effectiveDuration = durationSec ?? 60
    const fractions = effectiveDuration < 5
      ? [0.5]                                                                   // 1 frame
      : effectiveDuration < 15
        ? [0.2, 0.5, 0.8]                                                       // 3 frames
      : effectiveDuration < 60
        ? [0.08, 0.22, 0.36, 0.5, 0.64, 0.78, 0.92]                             // 7 frames
      : effectiveDuration < 600
        ? [0.05, 0.15, 0.27, 0.4, 0.5, 0.6, 0.73, 0.87, 0.95]                   // 9 frames
        : [0.03, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.97]            // 11 frames

    for (const frac of fractions) {
      const t = Math.round(effectiveDuration * frac)
      try {
        await page.evaluate((sec: number) => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const doc = (globalThis as any).document as { querySelectorAll(s: string): unknown[] } | undefined
          if (!doc) return
          const list = Array.from(doc.querySelectorAll('video')) as Array<{
            duration: number; currentTime: number; videoWidth: number; videoHeight: number; play(): Promise<void>
          }>
          list.sort((a, b) => (b.videoWidth * b.videoHeight) - (a.videoWidth * a.videoHeight))
          const v = list[0]
          if (!v) return
          try { v.currentTime = sec; void v.play() } catch { /* */ }
        }, t)
        // Longer paint settle — 1080p frame + decoded video chroma needs ~1.5s
        await page.waitForTimeout(1600)
        const buf = await page.screenshot({ type: 'jpeg', quality: 92, fullPage: false })
        if (buf.length > 5000) {
          frames.push({
            url: `playwright-frame-at-${t}s`,
            label: `frame-${Math.round(frac * 100)}%`,
            base64: Buffer.from(buf).toString('base64'),
            mimeType: 'image/jpeg',
          })
        }
      } catch { /* skip this frame */ }
    }
  } catch { /* whole path tolerated */ }
  finally {
    try { await context?.close() } catch { /* */ }
    try { await browser?.close() } catch { /* */ }
  }

  return { frames, ...(durationSec ? { durationSec } : {}) }
}

/**
 * Vision-capable LLM call: send transcript + metadata + the actual
 * frame images so the brain can describe what it SEES, not just what
 * was said. Tries Gemini 2.0 Flash first (cheap vision), then GPT-4o,
 * then Claude 3.5 Sonnet.
 */
async function analyzeFramesWithVision(
  frames: Array<{ url: string; base64: string; mimeType: string; label: string }>,
  meta: { title?: string; channel?: string; durationSec?: number; description?: string },
  transcript: string | undefined,
  operatorContext: string,
): Promise<{ summary?: string; visualHighlights?: string[]; keyMoments?: VideoAnalysis['keyMoments']; error?: string }> {
  if (frames.length === 0) return { error: 'no frames to analyze' }

  const metaBlock = [
    meta.title       ? `Title: ${meta.title}` : '',
    meta.channel     ? `Channel: ${meta.channel}` : '',
    meta.durationSec ? `Duration: ${Math.round(meta.durationSec / 60)} min` : '',
  ].filter(Boolean).join('\n')

  const transcriptBlock = transcript
    ? `\n\nTranscript (audio, verbatim):\n${transcript.slice(0, 60000)}`   // up from 8K → 60K
    : '\n\n(No transcript available — describe what you see, including any on-screen text you can read.)'

  const operatorBlock = operatorContext.trim()
    ? `\n\nOperator wants:\n${operatorContext.slice(0, 2000)}`
    : ''

  const frameLabels = frames.map((f, i) => `Frame ${i + 1}: ${f.label}`).join('\n')
  const promptText =
`You are a forensic-grade video analyst. ${frames.length} frames from the video are attached IN ORDER and labeled below. Your job: produce the most accurate, concrete, complete understanding possible. Describe what is ACTUALLY visible — no fabrication, no guessing. Read on-screen text precisely. Identify tools, UI, brands, locations, people (by visible role, not identification), techniques being demonstrated, and changes between frames.

${frameLabels}

${metaBlock}${transcriptBlock}${operatorBlock}

Return JSON only (no prose, no markdown):
{
  "summary": "6-10 sentences synthesizing what the video shows AND says. Cover: subject, what's being demonstrated/argued, who the audience is, the takeaway.",
  "visualHighlights": ["one factual sentence per frame describing exactly what's in it, in order"],
  "onScreenText": ["every legible text element you can read across the frames — UI labels, captions, slides, titles, code, signs"],
  "demonstratedActions": ["concrete actions/steps shown — e.g. 'opens VS Code', 'drags slider to 40%', 'pours coffee'"],
  "toolsAndUI": ["specific software, hardware, products, websites visible — name them when identifiable"],
  "keyMoments": [{"atSec": 0, "label": "what happens at this timestamp"}],
  "visualStyle": "1 sentence: production style (talking-head tutorial / cinematic vlog / screen recording / interview / etc.)",
  "colorPalette": ["dominant", "color", "names"],
  "audienceAndIntent": "1 sentence: who this is for and why they'd watch",
  "actionableTakeaways": ["bulleted concrete things a viewer could replicate or apply"]
}
Density and accuracy matter more than brevity. If a field is genuinely empty, return []. Never invent.`

  const providerErrors: string[] = []

  // ─── Try 1: Gemini (cheapest vision, handles inlineData well) ────────
  const geminiKey = process.env['GEMINI_API_KEY']
  if (geminiKey) {
    try {
      const parts: Array<Record<string, unknown>> = [{ text: promptText }]
      // Validate MIME — Gemini accepts image/{jpeg,png,webp,heic,heif}.
      // Anything else (text/html when oEmbed returned a wrapper, video/mp4
      // when ffmpeg failed earlier) causes a 400 the caller can't debug.
      const VALID_IMAGE_MIME = /^image\/(jpeg|jpg|png|webp|heic|heif)$/i
      for (const f of frames) {
        if (!VALID_IMAGE_MIME.test(f.mimeType)) {
          providerErrors.push(`gemini:invalid-mime ${f.mimeType}`)
          continue
        }
        parts.push({ inlineData: { mimeType: f.mimeType, data: f.base64 } })
      }
      if (parts.length === 1) {
        // All frames rejected for invalid MIME — surface to caller.
        providerErrors.push('gemini:no-valid-frames')
      }
      // Prefer Gemini 2.5 Pro (deeper vision reasoning); fall back to 2.0 Flash.
      // Pass the API key via x-goog-api-key header instead of the ?key= query
      // parameter — query strings leak to access logs, referer headers, and
      // any HTTP-debug tools the operator inspects.
      const geminiModel = process.env['GEMINI_VISION_MODEL'] ?? 'gemini-2.5-pro'
      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${geminiModel}:generateContent`, {
        method: 'POST',
        headers: {
          'Content-Type':    'application/json',
          'x-goog-api-key':  geminiKey,
        },
        body: JSON.stringify({
          contents: [{ role: 'user', parts }],
          generationConfig: { temperature: 0.15, maxOutputTokens: 8000, responseMimeType: 'application/json' },
        }),
        signal: AbortSignal.timeout(120_000),
      })
      if (res.ok) {
        const j = await res.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> }
        const text = j.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
        if (text) {
          const parsed = JSON.parse(text) as {
            summary?: string; visualHighlights?: string[]; keyMoments?: VideoAnalysis['keyMoments']
            visualStyle?: string; colorPalette?: string[]
            onScreenText?: string[]; demonstratedActions?: string[]; toolsAndUI?: string[]
            audienceAndIntent?: string; actionableTakeaways?: string[]
          }
          const out: { summary?: string; visualHighlights?: string[]; keyMoments?: VideoAnalysis['keyMoments'] } = {}
          if (parsed.summary) {
            const sections: string[] = [parsed.summary]
            if (parsed.visualStyle)          sections.push(`Production style: ${parsed.visualStyle}`)
            if (parsed.audienceAndIntent)    sections.push(`Audience & intent: ${parsed.audienceAndIntent}`)
            if (parsed.toolsAndUI?.length)   sections.push(`Tools / UI shown: ${parsed.toolsAndUI.join(', ')}`)
            if (parsed.demonstratedActions?.length) sections.push(`Actions demonstrated:\n- ${parsed.demonstratedActions.join('\n- ')}`)
            if (parsed.onScreenText?.length) sections.push(`On-screen text:\n- ${parsed.onScreenText.slice(0, 20).join('\n- ')}`)
            if (parsed.actionableTakeaways?.length) sections.push(`Actionable takeaways:\n- ${parsed.actionableTakeaways.join('\n- ')}`)
            if (parsed.colorPalette?.length) sections.push(`Color palette: ${parsed.colorPalette.join(', ')}`)
            out.summary = sections.join('\n\n')
          }
          if (parsed.visualHighlights) out.visualHighlights = parsed.visualHighlights.slice(0, 12)
          if (parsed.keyMoments)       out.keyMoments       = parsed.keyMoments.slice(0, 16)
          if (out.summary || out.visualHighlights || out.keyMoments) return out
        }
      } else {
        const body = await res.text().catch(() => '')
        providerErrors.push(`GEMINI_API_KEY:${res.status} ${body.slice(0, 200)}`)
      }
    } catch (e) { providerErrors.push(`GEMINI_API_KEY: ${(e as Error).message}`) }
  }

  // ─── Try 2: GPT-4o (vision-capable, takes image_url with data URI) ────
  const openaiKey = process.env['OPENAI_API_KEY']
  if (openaiKey) {
    try {
      const content: Array<Record<string, unknown>> = [{ type: 'text', text: promptText }]
      for (const f of frames) {
        // 'detail: high' forces full-resolution analysis (much better OCR + fine detail)
        content.push({ type: 'image_url', image_url: { url: `data:${f.mimeType};base64,${f.base64}`, detail: 'high' } })
      }
      const openaiModel = process.env['OPENAI_VISION_MODEL'] ?? 'gpt-4o'
      const res = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${openaiKey}` },
        body: JSON.stringify({
          model: openaiModel,
          messages: [
            { role: 'system', content: 'Forensic-grade video frame analyst. Output strict JSON, no prose, no markdown.' },
            { role: 'user',   content },
          ],
          temperature: 0.15, max_tokens: 8000, response_format: { type: 'json_object' },
        }),
        signal: AbortSignal.timeout(120_000),
      })
      if (res.ok) {
        const j = await res.json() as { choices?: Array<{ message?: { content?: string } }> }
        const text = j.choices?.[0]?.message?.content ?? ''
        if (text) {
          const parsed = JSON.parse(text) as {
            summary?: string; visualHighlights?: string[]; keyMoments?: VideoAnalysis['keyMoments']
            visualStyle?: string; colorPalette?: string[]
            onScreenText?: string[]; demonstratedActions?: string[]; toolsAndUI?: string[]
            audienceAndIntent?: string; actionableTakeaways?: string[]
          }
          const out: { summary?: string; visualHighlights?: string[]; keyMoments?: VideoAnalysis['keyMoments'] } = {}
          if (parsed.summary) {
            const sections: string[] = [parsed.summary]
            if (parsed.visualStyle)          sections.push(`Production style: ${parsed.visualStyle}`)
            if (parsed.audienceAndIntent)    sections.push(`Audience & intent: ${parsed.audienceAndIntent}`)
            if (parsed.toolsAndUI?.length)   sections.push(`Tools / UI shown: ${parsed.toolsAndUI.join(', ')}`)
            if (parsed.demonstratedActions?.length) sections.push(`Actions demonstrated:\n- ${parsed.demonstratedActions.join('\n- ')}`)
            if (parsed.onScreenText?.length) sections.push(`On-screen text:\n- ${parsed.onScreenText.slice(0, 20).join('\n- ')}`)
            if (parsed.actionableTakeaways?.length) sections.push(`Actionable takeaways:\n- ${parsed.actionableTakeaways.join('\n- ')}`)
            if (parsed.colorPalette?.length) sections.push(`Color palette: ${parsed.colorPalette.join(', ')}`)
            out.summary = sections.join('\n\n')
          }
          if (parsed.visualHighlights) out.visualHighlights = parsed.visualHighlights.slice(0, 12)
          if (parsed.keyMoments)       out.keyMoments       = parsed.keyMoments.slice(0, 16)
          if (out.summary || out.visualHighlights || out.keyMoments) return out
        }
      } else {
        const body = await res.text().catch(() => '')
        providerErrors.push(`OPENAI_API_KEY:${res.status} ${body.slice(0, 200)}`)
      }
    } catch (e) { providerErrors.push(`OPENAI_API_KEY: ${(e as Error).message}`) }
  }

  // ─── Try 3: Anthropic Claude (vision via base64 image source) ──────────
  const anthropicKey = process.env['ANTHROPIC_API_KEY']
  if (anthropicKey) {
    try {
      const content: Array<Record<string, unknown>> = []
      for (const f of frames) {
        content.push({ type: 'image', source: { type: 'base64', media_type: f.mimeType, data: f.base64 } })
      }
      content.push({ type: 'text', text: promptText })
      const claudeModel = process.env['ANTHROPIC_VISION_MODEL'] ?? 'claude-opus-4-5'
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-api-key': anthropicKey, 'anthropic-version': '2023-06-01' },
        body: JSON.stringify({
          model: claudeModel, max_tokens: 8000, temperature: 0.15,
          messages: [{ role: 'user', content }],
        }),
        signal: AbortSignal.timeout(120_000),
      })
      if (res.ok) {
        const j = await res.json() as { content?: Array<{ text?: string }> }
        const raw = j.content?.[0]?.text ?? ''
        const m = raw.match(/\{[\s\S]*\}/)
        if (m) {
          try {
            const parsed = JSON.parse(m[0]) as {
              summary?: string; visualHighlights?: string[]; keyMoments?: VideoAnalysis['keyMoments']
              visualStyle?: string; colorPalette?: string[]
              onScreenText?: string[]; demonstratedActions?: string[]; toolsAndUI?: string[]
              audienceAndIntent?: string; actionableTakeaways?: string[]
            }
            const out: { summary?: string; visualHighlights?: string[]; keyMoments?: VideoAnalysis['keyMoments'] } = {}
            if (parsed.summary) {
              const sections: string[] = [parsed.summary]
              if (parsed.visualStyle)          sections.push(`Production style: ${parsed.visualStyle}`)
              if (parsed.audienceAndIntent)    sections.push(`Audience & intent: ${parsed.audienceAndIntent}`)
              if (parsed.toolsAndUI?.length)   sections.push(`Tools / UI shown: ${parsed.toolsAndUI.join(', ')}`)
              if (parsed.demonstratedActions?.length) sections.push(`Actions demonstrated:\n- ${parsed.demonstratedActions.join('\n- ')}`)
              if (parsed.onScreenText?.length) sections.push(`On-screen text:\n- ${parsed.onScreenText.slice(0, 20).join('\n- ')}`)
              if (parsed.actionableTakeaways?.length) sections.push(`Actionable takeaways:\n- ${parsed.actionableTakeaways.join('\n- ')}`)
              if (parsed.colorPalette?.length) sections.push(`Color palette: ${parsed.colorPalette.join(', ')}`)
              out.summary = sections.join('\n\n')
            }
            if (parsed.visualHighlights) out.visualHighlights = parsed.visualHighlights.slice(0, 12)
            if (parsed.keyMoments)       out.keyMoments       = parsed.keyMoments.slice(0, 16)
            if (out.summary || out.visualHighlights || out.keyMoments) return out
          } catch { /* fall through */ }
        }
      } else {
        const body = await res.text().catch(() => '')
        providerErrors.push(`ANTHROPIC_API_KEY:${res.status} ${body.slice(0, 200)}`)
      }
    } catch (e) { providerErrors.push(`ANTHROPIC_API_KEY: ${(e as Error).message}`) }
  }

  return { error: providerErrors.length > 0 ? providerErrors.join('; ').slice(0, 400) : 'no vision-capable provider configured' }
}

/**
 * Summarize via the platform's provider router — Groq/OpenAI/Anthropic/
 * Gemini are tried in priority order with retry + circuit breaker.
 *
 * (Gemini's fileData fileUri does not accept arbitrary YouTube URLs via
 * the public Generative Language API — only Files-API-uploaded blobs.
 * Text-based summarization is the reliable path; the transcript + page
 * metadata + operator question give plenty for a real understanding.)
 */
async function summarizeViaRouter(
  workspaceId: string,
  meta: { title?: string; channel?: string; durationSec?: number; description?: string },
  transcript: string | undefined,
  operatorContext: string,
): Promise<{ summary?: string; keyMoments?: VideoAnalysis['keyMoments']; visualHighlights?: string[] }> {
  // Skip entirely when we have nothing useful to send
  if (!transcript && !meta.description && !meta.title) return {}

  const metaBlock = [
    meta.title       ? `Title: ${meta.title}` : '',
    meta.channel     ? `Channel: ${meta.channel}` : '',
    meta.durationSec ? `Duration: ${Math.round(meta.durationSec / 60)} min` : '',
    meta.description ? `Description:\n${meta.description.slice(0, 1500)}` : '',
  ].filter(Boolean).join('\n')

  const transcriptBlock = transcript
    ? `\n\nTranscript:\n${transcript.slice(0, 12_000)}`
    : ''

  const operatorBlock = operatorContext.trim()
    ? `\n\nOperator wants:\n${operatorContext.slice(0, 1000)}`
    : ''

  const hasGroundTruth = !!(transcript || (meta.description && meta.description.length > 200))
  const userPrompt = hasGroundTruth ? `Analyze this video. You have metadata + transcript (when available).

${metaBlock}${transcriptBlock}${operatorBlock}

Return JSON only (no prose outside, no markdown fences) with shape:
{
  "summary": "4-5 sentence factual summary of what the video covers",
  "keyMoments": [{"atSec": 0, "label": "concrete point"}, ...],
  "visualHighlights": ["one-line visual description", ...]
}
Be factual. Cite concrete claims from the transcript. No fabrication.` : `You have only the metadata for a video (transcript was unavailable). Use your training knowledge if you recognize this specific video; otherwise note clearly that you only have metadata.

${metaBlock}${operatorBlock}

Return JSON only with shape:
{
  "summary": "4-5 sentence summary. If you recognize the video from training, summarize it. If not, say 'Based on title only: ...' and describe what the video likely covers given the title + channel.",
  "keyMoments": [{"atSec": 0, "label": "guess based on the title"}, ...],   // 3-6 entries; mark with 'likely' if guessing
  "visualHighlights": []
}
Always be explicit about what you know vs guess. No fabrication.`

  try {
    // Direct provider call via the simplest available — Groq first, then
    // OpenAI/Anthropic/Gemini. Avoids the streamChat conversational
    // overhead since we don't need a persisted conversation here.
    const candidates: Array<{ envVar: string; url: string; family: 'openai' | 'anthropic' | 'gemini'; model: string }> = [
      { envVar: 'GROQ_API_KEY',      url: 'https://api.groq.com/openai/v1/chat/completions',  family: 'openai',    model: 'llama-3.3-70b-versatile' },
      { envVar: 'GEMINI_API_KEY',    url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent', family: 'gemini', model: 'gemini-2.0-flash' },
      { envVar: 'OPENAI_API_KEY',    url: 'https://api.openai.com/v1/chat/completions',        family: 'openai',    model: 'gpt-4o-mini' },
      { envVar: 'ANTHROPIC_API_KEY', url: 'https://api.anthropic.com/v1/messages',             family: 'anthropic', model: 'claude-3-5-haiku-latest' },
    ]
    let finalContent = ''
    const providerErrors: string[] = []
    for (const c of candidates) {
      const key = process.env[c.envVar]
      if (!key) continue
      try {
        if (c.family === 'openai') {
          const res = await fetch(c.url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
            body: JSON.stringify({
              model: c.model, temperature: 0.2, max_tokens: 1500,
              messages: [
                { role: 'system', content: 'You are a video-analysis assistant. Output JSON only.' },
                { role: 'user',   content: userPrompt },
              ],
              response_format: { type: 'json_object' },
            }),
            signal: AbortSignal.timeout(30_000),
          })
          if (!res.ok) {
            const body = await res.text().catch(() => '')
            providerErrors.push(`${c.envVar}:${res.status} ${body.slice(0, 200)}`)
            continue
          }
          const j = await res.json() as { choices?: Array<{ message?: { content?: string } }> }
          finalContent = j.choices?.[0]?.message?.content ?? ''
          if (finalContent) break
        } else if (c.family === 'anthropic') {
          const res = await fetch(c.url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' },
            body: JSON.stringify({
              model: c.model, max_tokens: 1500, temperature: 0.2,
              system: 'You are a video-analysis assistant. Output JSON only.',
              messages: [{ role: 'user', content: userPrompt }],
            }),
            signal: AbortSignal.timeout(30_000),
          })
          if (!res.ok) {
            const body = await res.text().catch(() => '')
            providerErrors.push(`${c.envVar}:${res.status} ${body.slice(0, 200)}`)
            continue
          }
          const j = await res.json() as { content?: Array<{ text?: string }> }
          finalContent = j.content?.[0]?.text ?? ''
          if (finalContent) break
        } else if (c.family === 'gemini') {
          // Gemini API: use the x-goog-api-key header instead of ?key= query
          // param. The query-param form leaks the key into proxy access
          // logs, browser referer headers, and HAR exports — the header
          // form keeps it scoped to the request body's TLS envelope.
          const res = await fetch(c.url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'x-goog-api-key': key },
            body: JSON.stringify({
              contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
              systemInstruction: { parts: [{ text: 'You are a video-analysis assistant. Output JSON only.' }] },
              generationConfig: { temperature: 0.2, maxOutputTokens: 1500, responseMimeType: 'application/json' },
            }),
            signal: AbortSignal.timeout(30_000),
          })
          if (!res.ok) {
            const body = await res.text().catch(() => '')
            providerErrors.push(`${c.envVar}:${res.status} ${body.slice(0, 200)}`)
            continue
          }
          const j = await res.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> }
          finalContent = j.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
          if (finalContent) break
        }
      } catch (e) { providerErrors.push(`${c.envVar}: ${(e as Error).message}`); continue }
    }

    if (!finalContent) {
      // Surface ALL provider attempts so the operator + chat downstream
      // see exactly which keys hit quota / which models failed.
      if (providerErrors.length > 0) {
        const detail = providerErrors.map(e => {
          // Trim verbose JSON error bodies down to the human-readable reason
          const m = e.match(/"message":"([^"]+)"/)
          const reason = m?.[1] ?? e
          const env = e.split(':')[0]
          return `${env}: ${reason.slice(0, 120)}`
        }).join('; ')
        return { summary: `_(LLM summary unavailable — all configured providers failed: ${detail})_` }
      }
      return { summary: '_(LLM summary unavailable — no provider keys configured)_' }
    }
    const final = { content: finalContent }
    // ref so type checker stays happy if we never enter the loop
    void workspaceId
    // The model may wrap JSON in ```json``` fences or prose — strip if so
    let text = final.content.trim()
    const fenceMatch = text.match(/```(?:json)?\s*\n([\s\S]*?)```/)
    if (fenceMatch) text = fenceMatch[1]!.trim()
    const jsonMatch = text.match(/\{[\s\S]*\}/)
    const out: { summary?: string; keyMoments?: VideoAnalysis['keyMoments']; visualHighlights?: string[] } = {}
    if (jsonMatch) {
      try {
        const parsed = JSON.parse(jsonMatch[0]) as { summary?: string; keyMoments?: VideoAnalysis['keyMoments']; visualHighlights?: string[] }
        if (parsed.summary)          out.summary = parsed.summary
        if (parsed.keyMoments)       out.keyMoments = parsed.keyMoments.slice(0, 12)
        if (parsed.visualHighlights) out.visualHighlights = parsed.visualHighlights.slice(0, 12)
      } catch { /* fall through */ }
    }
    // Fallback: if JSON parse failed but we got text, use it as the summary
    if (!out.summary && final.content.trim().length > 50) {
      out.summary = final.content.trim().slice(0, 1500)
    }
    return out
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error('[video-analyzer] summarizeViaRouter failed:', (e as Error).message)
    return {}
  }
}

/**
 * Whisper transcription for non-YouTube sources. Uses yt-dlp + ffmpeg to
 * extract the audio track to a 16kHz mono mp3, then sends to Groq Whisper
 * (whisper-large-v3, free tier, very fast) or OpenAI Whisper as fallback.
 * Returns transcript text or undefined if unavailable.
 */
async function transcribeViaWhisper(url: string): Promise<{ transcript?: string; transcriptLang?: string }> {
  // URL validation — yt-dlp is called via spawn() with an args array (no
  // shell), so there's no command-injection vector, but a malformed URL
  // wastes 60+ seconds of yt-dlp's network timeout before failing. Reject
  // non-http(s) URLs up front.
  try {
    const u = new URL(url)
    if (u.protocol !== 'http:' && u.protocol !== 'https:') return {}
  } catch { return {} }

  // Lazy-load — these are heavy imports
  const { spawn } = await import('node:child_process')
  const { existsSync, mkdirSync, readFileSync, unlinkSync } = await import('node:fs')
  const { join } = await import('node:path')
  const { tmpdir } = await import('node:os')

  const ytdlp  = process.env['YTDLP_BIN']  ?? 'yt-dlp'
  const ffmpeg = process.env['FFMPEG_BIN'] ?? 'ffmpeg'
  const dir = join(tmpdir(), 'novan-video-audio')
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  const stamp = Date.now().toString(36)
  const outBase = join(dir, `audio-${stamp}`)
  const outAudio = `${outBase}.mp3`

  // 1. Download audio-only mp3
  const dlOk = await new Promise<boolean>((resolve) => {
    let proc
    try {
      proc = spawn(ytdlp, [
        '-x', '--audio-format', 'mp3', '--audio-quality', '5',
        '--no-playlist', '-o', `${outBase}.%(ext)s`,
        '--ffmpeg-location', ffmpeg, url,
      ], { windowsHide: true })
    } catch { resolve(false); return }
    proc.on('error', () => resolve(false))
    proc.on('close', (code) => resolve(code === 0 && existsSync(outAudio)))
  })
  if (!dlOk) return {}

  try {
    const audioBuf = readFileSync(outAudio)
    // 2. Try Groq Whisper first (whisper-large-v3-turbo is fast + free)
    const groqKey = process.env['GROQ_API_KEY']
    if (groqKey) {
      try {
        const form = new FormData()
        form.append('file', new Blob([new Uint8Array(audioBuf)], { type: 'audio/mpeg' }), 'audio.mp3')
        form.append('model', process.env['GROQ_WHISPER_MODEL'] ?? 'whisper-large-v3')
        form.append('response_format', 'verbose_json')
        const r = await fetch('https://api.groq.com/openai/v1/audio/transcriptions', {
          method: 'POST',
          headers: { Authorization: `Bearer ${groqKey}` },
          body: form,
          signal: AbortSignal.timeout(180_000),
        })
        if (r.ok) {
          const j = await r.json() as { text?: string; language?: string }
          if (j.text && j.text.length > 5) {
            const out: { transcript?: string; transcriptLang?: string } = { transcript: j.text }
            if (j.language) out.transcriptLang = j.language
            return out
          }
        }
      } catch { /* fall through to openai */ }
    }
    // 3. OpenAI Whisper fallback
    const openaiKey = process.env['OPENAI_API_KEY']
    if (openaiKey) {
      try {
        const form = new FormData()
        form.append('file', new Blob([new Uint8Array(audioBuf)], { type: 'audio/mpeg' }), 'audio.mp3')
        form.append('model', 'whisper-1')
        form.append('response_format', 'verbose_json')
        const r = await fetch('https://api.openai.com/v1/audio/transcriptions', {
          method: 'POST',
          headers: { Authorization: `Bearer ${openaiKey}` },
          body: form,
          signal: AbortSignal.timeout(300_000),
        })
        if (r.ok) {
          const j = await r.json() as { text?: string; language?: string }
          if (j.text && j.text.length > 5) {
            const out: { transcript?: string; transcriptLang?: string } = { transcript: j.text }
            if (j.language) out.transcriptLang = j.language
            return out
          }
        }
      } catch { /* */ }
    }
    return {}
  } finally {
    try { unlinkSync(outAudio) } catch { /* */ }
  }
}

/** Generic page fetch — for non-YouTube URLs, pull OpenGraph metadata. */
async function fetchOpenGraph(url: string): Promise<{ title?: string; description?: string; thumbnail?: string }> {
  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0 Novan/1.0' },
      signal: AbortSignal.timeout(8000),
    })
    if (!res.ok) return {}
    const html = await res.text()
    const pick = (prop: string): string | undefined => {
      const re = new RegExp(`<meta[^>]+(?:property|name)=["']${prop}["'][^>]+content=["']([^"']+)["']`, 'i')
      const m = html.match(re)
      return m?.[1]
    }
    const out: { title?: string; description?: string; thumbnail?: string } = {}
    const t = pick('og:title');       if (t) out.title       = t
    const d = pick('og:description'); if (d) out.description = d
    const i = pick('og:image');       if (i) out.thumbnail   = i
    return out
  } catch (e) {
    console.error('[video-analyzer] og-meta fetch failed:', (e as Error).message)
    return {}
  }
}

/**
 * Public entry — analyze a video URL with optional operator context.
 * `context` is whatever the operator typed alongside the URL ("summarize",
 * "code this up", "what tools do they use", etc). Gemini uses it to
 * focus the analysis if available.
 */
export async function analyzeVideo(url: string, context = '', workspaceId = 'default'): Promise<VideoAnalysis> {
  const now = Date.now()
  const source = classifyVideoUrl(url)
  const out: VideoAnalysis = { ok: false, url, source, fetchedAt: now }

  try {
    // ─── Step 1: source-specific metadata + transcript when available ───
    let videoId: string | null = null
    if (source === 'youtube') {
      videoId = youtubeVideoId(url)
      if (videoId) {
        const [oembed, tr] = await Promise.all([
          fetchYouTubeOEmbed(url),
          fetchYouTubeTranscript(videoId),
        ])
        Object.assign(out, oembed, tr)
      }
    } else if (source !== 'unknown') {
      // Vimeo/TikTok/Twitter/direct mp4 — pull OpenGraph + Whisper transcript
      // in parallel. Transcript via Whisper is the single biggest quality
      // win for non-YouTube videos (gives the brain the actual words said).
      const [og, whisper] = await Promise.all([
        fetchOpenGraph(url),
        transcribeViaWhisper(url).catch((e: unknown) => {
          // Silent fallback was hiding real failures from the operator —
          // log the message so a failing yt-dlp / Whisper outage shows up
          // in logs even though the analysis itself degrades gracefully.
          console.error('[video-analyzer] Whisper transcription failed:', (e as Error).message)
          return {} as { transcript?: string; transcriptLang?: string }
        }),
      ])
      Object.assign(out, og)
      if (whisper.transcript)     out.transcript     = whisper.transcript
      if (whisper.transcriptLang) out.transcriptLang = whisper.transcriptLang
    }

    // ─── Step 2: assemble frame set ─────────────────────────────────────
    // Always try playwright for actual mid-video frames (works on any
    // page with a <video> element). For YouTube, also fetch the cover
    // thumbnail since it's free + reliable.
    const frames: Array<{ url: string; base64: string; mimeType: string; label: string }> = []

    if (source === 'youtube' && videoId) {
      const thumb = await fetchYouTubeThumbnail(videoId)
      if (thumb) frames.push(thumb)
    }

    // Generic playwright capture — handles youtube/vimeo/tiktok/twitter/
    // direct mp4. The probe inside reads the actual duration off the
    // <video> element so we don't need to know it beforehand.
    const pw = await captureVideoFramesViaPlaywright(source, url, videoId, out.durationSec)
    if (pw.durationSec && !out.durationSec) out.durationSec = pw.durationSec
    frames.push(...pw.frames)

    out.framesAnalyzed = frames.length
    out.framesUrls = frames.map(f => f.url)

    // ─── Step 3: vision LLM ─────────────────────────────────────────────
    const metaForLLM: { title?: string; channel?: string; durationSec?: number; description?: string } = {}
    if (out.title)       metaForLLM.title       = out.title
    if (out.channel)     metaForLLM.channel     = out.channel
    if (out.durationSec) metaForLLM.durationSec = out.durationSec
    if (out.description) metaForLLM.description = out.description

    if (frames.length > 0) {
      const vis = await analyzeFramesWithVision(frames, metaForLLM, out.transcript, context)
      if (vis.summary || vis.visualHighlights?.length) {
        if (vis.summary)          out.summary          = vis.summary
        if (vis.visualHighlights) out.visualHighlights = vis.visualHighlights
        if (vis.keyMoments)       out.keyMoments       = vis.keyMoments
        out.ok = true
        return out
      }
      if (vis.error) out.error = `vision: ${vis.error}`
    }

    // ─── Step 4: text-only fallback ─────────────────────────────────────
    const g = await summarizeViaRouter(workspaceId, metaForLLM, out.transcript, context)
    Object.assign(out, g)
    out.ok = !!(out.title || out.transcript || out.summary || frames.length > 0)
    if (!out.ok) out.error = out.error ?? 'no usable metadata, transcript, or frames found'

    // Emit a workspace-scoped event so the analysis is queryable per
    // workspace + visible in the /events stream. Without this, the
    // analysis result lives only in the function's return value and the
    // workspace ID parameter is effectively unused for persistence.
    try {
      const { db } = await import('../db/client.js')
      const { events } = await import('../db/schema.js')
      const { v7: uuidv7 } = await import('uuid')
      await db.insert(events).values({
        id: uuidv7(),
        type: 'video.analyzed',
        workspaceId,
        payload: {
          url, source, ok: out.ok,
          title: out.title ?? null,
          channel: out.channel ?? null,
          durationSec: out.durationSec ?? null,
          framesAnalyzed: out.framesAnalyzed ?? 0,
          hasTranscript: !!out.transcript,
          hasVisionAnalysis: !!out.summary,
          error: out.error ?? null,
        },
        traceId: uuidv7(), correlationId: uuidv7(), causationId: null,
        source: 'video-analyzer', version: 1, createdAt: Date.now(),
      }).catch((e: Error) => { console.error('[video-analyzer]', e.message); return null })
    } catch { /* tolerated — emit is best-effort */ }

    return out
  } catch (e) {
    out.error = (e as Error).message
    return out
  }
}

/** Extract any video URLs from a free-form text blob. */
export function extractVideoUrls(text: string): string[] {
  if (!text) return []
  const urlRegex = /\bhttps?:\/\/[^\s<>"']+/g
  const matches = text.match(urlRegex) ?? []
  return matches.filter(u => isLikelyVideoPage(u)).slice(0, 3)
}

/** Render an analysis as a compact context block for chat prompts. */
export function renderAnalysisForChat(a: VideoAnalysis): string {
  const lines: string[] = [`🎬 **Video analyzed**: ${a.url}`]
  if (a.title)   lines.push(`Title: ${a.title}`)
  if (a.channel) lines.push(`Channel: ${a.channel}`)
  if (a.durationSec) lines.push(`Duration: ${Math.round(a.durationSec / 60)} min`)
  if (a.framesAnalyzed && a.framesAnalyzed > 0) {
    lines.push(`Frames seen: ${a.framesAnalyzed} (brain has visual context)`)
  }
  if (a.summary) lines.push(`\nSummary:\n${a.summary}`)
  if (a.visualHighlights && a.visualHighlights.length > 0) {
    lines.push('\nWhat the brain SEES in the video:')
    for (const vh of a.visualHighlights.slice(0, 8)) lines.push(`  · ${vh}`)
  }
  if (a.keyMoments && a.keyMoments.length > 0) {
    lines.push('\nKey moments (audio + visual):')
    for (const km of a.keyMoments.slice(0, 8)) {
      const mm = Math.floor(km.atSec / 60), ss = (km.atSec % 60).toString().padStart(2, '0')
      lines.push(`  ${mm}:${ss} — ${km.label}`)
    }
  }
  if (a.transcript && !a.summary) {
    lines.push(`\nTranscript (excerpt):\n${a.transcript.slice(0, 2000)}…`)
  }
  if (a.error) lines.push(`\n_(partial: ${a.error})_`)
  return lines.join('\n')
}
