# Install-AutoStart.ps1
#
# Makes Novan run 24/7 on this Windows host:
#   1. Configures Docker Desktop to start with Windows (background, no UI)
#   2. Creates a Scheduled Task that boots: Docker → postgres+redis → API → workers
#   3. Sets the power plan to keep the machine awake when AC-plugged-in
#   4. Sets the laptop-lid-closed action to "Do nothing" (still runs when closed)
#
# Honest limit: a *powered-off* laptop runs nothing. For true off-host 24/7
# use deploy/fly.io (see deploy/README.md). This script makes the local
# host run as continuously as a laptop can.
#
# Run as Administrator from the repo root:
#   powershell -ExecutionPolicy Bypass -File scripts\Install-AutoStart.ps1
#
# To uninstall: scripts\Install-AutoStart.ps1 -Uninstall

param([switch]$Uninstall)

$ErrorActionPreference = 'Continue'

function Need-Admin {
  $id = [Security.Principal.WindowsIdentity]::GetCurrent()
  $p  = New-Object Security.Principal.WindowsPrincipal($id)
  if (-not $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host 'This script must run as Administrator.' -ForegroundColor Red
    exit 1
  }
}
Need-Admin

$ROOT = (Get-Item (Split-Path $PSScriptRoot -Parent)).FullName
$TASK = 'Novan AutoStart'

if ($Uninstall) {
  Write-Host "Removing scheduled task '$TASK'..."
  schtasks /Delete /TN "$TASK" /F 2>&1 | Out-Null
  Write-Host 'Reverting power plan + lid action to defaults...'
  powercfg /setacvalueindex SCHEME_CURRENT SUB_BUTTONS LIDACTION 1
  powercfg /change standby-timeout-ac 30
  powercfg /setactive SCHEME_CURRENT
  Write-Host 'Done. Docker Desktop autostart untouched (uncheck it in Docker settings if needed).'
  exit 0
}

# Power plan
Write-Host 'Configuring power plan (AC: never sleep, lid does nothing)...'
powercfg /change standby-timeout-ac 0
powercfg /change hibernate-timeout-ac 0
powercfg /change disk-timeout-ac 0
powercfg /change monitor-timeout-ac 30
powercfg /setacvalueindex SCHEME_CURRENT SUB_BUTTONS LIDACTION 0
powercfg /setactive SCHEME_CURRENT

# Docker Desktop autostart minimized
$dockerExe = 'C:\Program Files\Docker\Docker\Docker Desktop.exe'
$startupShortcut = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\Docker Desktop.lnk"
if (Test-Path $dockerExe) {
  if (-not (Test-Path $startupShortcut)) {
    Write-Host 'Adding Docker Desktop to Startup folder (minimized)...'
    $WshShell = New-Object -ComObject WScript.Shell
    $sc = $WshShell.CreateShortcut($startupShortcut)
    $sc.TargetPath  = $dockerExe
    $sc.WindowStyle = 7
    $sc.Save()
  } else { Write-Host 'Docker Desktop startup shortcut already present.' }
  $dockerSettings = "$env:APPDATA\Docker\settings.json"
  if (Test-Path $dockerSettings) {
    try {
      $json = Get-Content $dockerSettings -Raw | ConvertFrom-Json
      $json | Add-Member -NotePropertyName openUIOnStartupDisabled -NotePropertyValue $true -Force
      $json | Add-Member -NotePropertyName autoStart -NotePropertyValue $true -Force
      $json | ConvertTo-Json -Depth 10 | Set-Content $dockerSettings -Encoding utf8
      Write-Host 'Docker settings updated (autostart + minimized UI).'
    } catch { Write-Host 'Could not update Docker settings.json automatically.' -ForegroundColor Yellow }
  }
} else {
  Write-Host 'Docker Desktop not found at expected path — skipping its autostart.' -ForegroundColor Yellow
}

# Generate the boot script
$bootScript = Join-Path $ROOT 'scripts\AutoStart-Boot.ps1'
Set-Content $bootScript -Encoding utf8 -Value @"
# Auto-generated by Install-AutoStart.ps1
# Boots the full Novan stack. Re-run is idempotent — only starts things
# that aren't already running.
`$ErrorActionPreference = 'Continue'
`$ROOT = '$ROOT'
Set-Location `$ROOT

# 1. Wait for Docker engine
for (`$i = 0; `$i -lt 24; `$i++) {
  try { docker ps *>`$null; if (`$LASTEXITCODE -eq 0) { break } } catch {}
  Start-Sleep -Seconds 5
}

# 2. Start postgres + redis containers
docker start ops-platform-postgres-1 ops-platform-redis-1 *>`$null

# 3. API
`$apiUp = `$null -ne (Get-NetTCPConnection -LocalPort 3001 -State Listen -ErrorAction SilentlyContinue | Where-Object { `$_.LocalAddress -eq '0.0.0.0' })
if (-not `$apiUp) {
  `$apiDir = Join-Path `$ROOT 'apps\api'
  `$logDir = Join-Path `$ROOT '.launch-logs'
  if (-not (Test-Path `$logDir)) { New-Item -ItemType Directory `$logDir | Out-Null }
  Start-Process -FilePath 'pnpm' -ArgumentList 'dev' ``
    -WorkingDirectory `$apiDir -WindowStyle Hidden ``
    -RedirectStandardOutput (Join-Path `$logDir 'auto-api.log') ``
    -RedirectStandardError  (Join-Path `$logDir 'auto-api.err.log')
}

# 4. Workers — start any that aren't running
`$WORKERS = @('analytics-worker','briefing-worker','browser-worker','learning-worker',
            'memory-worker','notifications-worker','optimization-worker','recovery-worker',
            'workflow-worker')
foreach (`$w in `$WORKERS) {
  `$running = Get-WmiObject Win32_Process | Where-Object { `$_.CommandLine -like ('*workers\' + `$w + '*') -and `$_.Name -eq 'node.exe' }
  if (-not `$running) {
    `$wDir = Join-Path `$ROOT (Join-Path 'workers' `$w)
    if (Test-Path `$wDir) {
      `$logName = Join-Path `$ROOT (Join-Path '.launch-logs' ('auto-' + `$w + '.log'))
      Start-Process -FilePath 'pnpm' -ArgumentList 'dev' ``
        -WorkingDirectory `$wDir -WindowStyle Hidden ``
        -RedirectStandardOutput `$logName -RedirectStandardError ("`$logName" + '.err')
    }
  }
}

# 5. Web dev server
`$webUp = `$null -ne (Get-NetTCPConnection -LocalPort 3000 -State Listen -ErrorAction SilentlyContinue)
if (-not `$webUp) {
  `$webDir = Join-Path `$ROOT 'apps\web'
  Start-Process -FilePath 'pnpm' -ArgumentList 'dev' ``
    -WorkingDirectory `$webDir -WindowStyle Hidden ``
    -RedirectStandardOutput (Join-Path `$ROOT '.launch-logs\auto-web.log') ``
    -RedirectStandardError  (Join-Path `$ROOT '.launch-logs\auto-web.err.log')
}
"@

# Recreate scheduled task
schtasks /Delete /TN "$TASK" /F 2>&1 | Out-Null
$xmlPath = Join-Path $env:TEMP 'novan-autostart.xml'
$xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <Triggers>
    <LogonTrigger><Enabled>true</Enabled><Delay>PT60S</Delay></LogonTrigger>
    <BootTrigger><Enabled>true</Enabled><Delay>PT120S</Delay></BootTrigger>
    <CalendarTrigger>
      <StartBoundary>2026-01-01T00:00:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay><DaysInterval>1</DaysInterval></ScheduleByDay>
      <Repetition>
        <Interval>PT5M</Interval>
        <Duration>P1D</Duration>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>$env:USERDOMAIN\$env:USERNAME</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>false</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings><StopOnIdleEnd>false</StopOnIdleEnd><RestartOnIdle>false</RestartOnIdle></IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>true</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>5</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File "$bootScript"</Arguments>
    </Exec>
  </Actions>
</Task>
"@
$xml | Out-File -FilePath $xmlPath -Encoding Unicode
schtasks /Create /TN "$TASK" /XML "$xmlPath" /F | Out-Null
Remove-Item $xmlPath -Force

Write-Host ''
Write-Host '─── Done ───' -ForegroundColor Green
Write-Host "Scheduled task: $TASK"
Write-Host '  Fires at logon (60s delay), at boot (2min delay), and every 5 min'
Write-Host '  Wakes the machine if asleep; idempotent'
Write-Host "Boot script: $bootScript"
Write-Host ''
Write-Host 'Power plan: AC plugged-in = never sleep, lid does nothing'
Write-Host 'Docker:     starts with Windows, minimized (no UI window)'
Write-Host ''
Write-Host 'Test now:  schtasks /Run /TN "Novan AutoStart"'
Write-Host 'Uninstall: powershell -File scripts\Install-AutoStart.ps1 -Uninstall'
