/**
 * Code Proposals — operator review surface for proposals generated by
 * the autonomous mind.
 */
import React, { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Code2, CheckCircle2, XCircle } from 'lucide-react'
import { api } from '../api.js'
import { useWorkspace } from '../contexts/WorkspaceContext.js'

interface Proposal {
  id: string; title: string; summary: string
  capabilityId: string | null; status: string; riskLevel: string
  estimatedLoc: number
  filesToCreate: Array<{ path: string; purpose: string; estLoc: number }>
  filesToModify: Array<{ path: string; purpose: string; estLoc: number }>
  testsRequired: Array<{ description: string; covers: string }>
  reasoning: string[]; createdAt: number
}

const RISK: Record<string, string> = {
  low:      'text-emerald-300 bg-emerald-500/15 border-emerald-500/30',
  medium:   'text-sky-300 bg-sky-500/15 border-sky-500/30',
  high:     'text-amber-300 bg-amber-500/15 border-amber-500/30',
  critical: 'text-red-300 bg-red-500/15 border-red-500/30',
}

export default function CodeProposalsPage() {
  const { workspaceId } = useWorkspace()
  const qc = useQueryClient()
  const [filter, setFilter] = useState<'proposed' | 'approved' | 'rejected' | 'all'>('proposed')
  const [expanded, setExpanded] = useState<string | null>(null)

  const proposals = useQuery({
    queryKey: ['proposals', workspaceId, filter],
    queryFn:  () => api.get<{ data: Proposal[] }>(`/api/v1/self/proposals?workspace_id=${workspaceId}${filter !== 'all' ? `&status=${filter}` : ''}`),
    refetchInterval: 30_000,
  })

  const setStatus = useMutation({
    mutationFn: ({ id, status }: { id: string; status: string }) =>
      api.post(`/api/v1/self/proposals/${id}/status`, { workspace_id: workspaceId, status }),
    onSuccess:  () => qc.invalidateQueries({ queryKey: ['proposals', workspaceId] }),
  })

  const rows = proposals.data?.data ?? []
  return (
    <div className="p-6 space-y-4 max-w-7xl mx-auto">
      <div className="flex items-center gap-3">
        <Code2 className="w-5 h-5 text-sky-400" />
        <h1 className="text-xl font-semibold">Code Proposals</h1>
        <span className="text-xs text-[var(--text-muted)] ml-1">{rows.length} {filter}</span>
        <div className="ml-auto flex items-center gap-1">
          {(['proposed', 'approved', 'rejected', 'all'] as const).map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className={`px-2 py-1 text-xs rounded border ${filter === f ? 'border-sky-500/50 text-sky-300 bg-sky-500/10' : 'border-[var(--border)] text-[var(--text-muted)] hover:bg-[var(--surface-hover)]'}`}>
              {f}
            </button>
          ))}
        </div>
      </div>

      {rows.length === 0 ? (
        <div className="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-5 py-8 text-center text-sm text-[var(--text-muted)]">
          No {filter} proposals. The autonomous mind generates these every 10min when it detects buildable capability gaps.
        </div>
      ) : (
        <ul className="space-y-2">
          {rows.map(p => {
            const isOpen = expanded === p.id
            return (
              <li key={p.id} className="rounded-lg border border-[var(--border)] bg-[var(--surface)]">
                <div className="px-4 py-3 flex items-center gap-3">
                  <span className={`px-1.5 py-0.5 rounded text-[10px] border ${RISK[p.riskLevel] ?? RISK.medium}`}>{p.riskLevel}</span>
                  <span className="text-xs text-[var(--text-muted)] font-mono">~{p.estimatedLoc} LOC</span>
                  <button onClick={() => setExpanded(isOpen ? null : p.id)} className="flex-1 text-left text-sm hover:underline">
                    {p.title}
                  </button>
                  <span className="text-xs text-[var(--text-muted)] font-mono">{p.status}</span>
                  {p.status === 'proposed' && (
                    <>
                      <button onClick={() => setStatus.mutate({ id: p.id, status: 'approved' })}
                        className="p-1 hover:bg-emerald-500/10 rounded" title="Approve">
                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      </button>
                      <button onClick={() => setStatus.mutate({ id: p.id, status: 'rejected' })}
                        className="p-1 hover:bg-red-500/10 rounded" title="Reject">
                        <XCircle className="w-4 h-4 text-red-400" />
                      </button>
                    </>
                  )}
                </div>
                {isOpen && (
                  <div className="px-4 py-3 border-t border-[var(--border)] text-xs space-y-2">
                    <p className="text-[var(--text-muted)]">{p.summary}</p>
                    <ul className="text-[var(--text-muted)] space-y-0.5">
                      {p.reasoning.map((r, i) => <li key={i}>• {r}</li>)}
                    </ul>
                    {p.filesToCreate.length > 0 && (
                      <div>
                        <div className="text-emerald-400 font-medium">Files to create:</div>
                        <ul className="font-mono text-[10px] text-[var(--text-muted)]">
                          {p.filesToCreate.map((f, i) => <li key={i}>+ {f.path} <span className="opacity-60">(~{f.estLoc} LOC · {f.purpose})</span></li>)}
                        </ul>
                      </div>
                    )}
                    {p.filesToModify.length > 0 && (
                      <div>
                        <div className="text-amber-400 font-medium">Files to modify:</div>
                        <ul className="font-mono text-[10px] text-[var(--text-muted)]">
                          {p.filesToModify.map((f, i) => <li key={i}>~ {f.path} <span className="opacity-60">(~{f.estLoc} LOC · {f.purpose})</span></li>)}
                        </ul>
                      </div>
                    )}
                    {p.testsRequired.length > 0 && (
                      <div>
                        <div className="text-sky-400 font-medium">Tests required:</div>
                        <ul className="text-[var(--text-muted)]">
                          {p.testsRequired.map((t, i) => <li key={i}>• {t.description}</li>)}
                        </ul>
                      </div>
                    )}
                  </div>
                )}
              </li>
            )
          })}
        </ul>
      )}
    </div>
  )
}
