/**
 * Code Patches — view patches generated by the code-agent.
 * Operator reviews patch text + safety report + sandbox result, then
 * manually commits via git outside the platform.
 */
import React, { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Hammer, ShieldCheck, ShieldAlert, FileCode } from 'lucide-react'
import { api } from '../api.js'
import { useWorkspace } from '../contexts/WorkspaceContext.js'

interface Patch {
  id: string; proposalId: string; status: string; agent: string
  files: Array<{ path: string; contents: string; op: string }>
  safetyReport: { ok: boolean; blockedReasons: string[] }
  sandboxReport: { ok: boolean; typecheck: { ran: boolean; passed: boolean; output: string }; errors: string[] }
  blockReason: string | null
  tokensUsed: number; costUsdUsed: number
  createdAt: number
}

const STATUS: Record<string, string> = {
  pending:         'text-slate-300 bg-slate-500/15 border-slate-500/30',
  generated:       'text-sky-300 bg-sky-500/15 border-sky-500/30',
  safety_blocked:  'text-red-300 bg-red-500/15 border-red-500/30',
  sandbox_failed:  'text-amber-300 bg-amber-500/15 border-amber-500/30',
  validated:       'text-emerald-300 bg-emerald-500/15 border-emerald-500/30',
  merged:          'text-purple-300 bg-purple-500/15 border-purple-500/30',
  rejected:        'text-red-300 bg-red-500/15 border-red-500/30',
}

export default function CodePatchesPage() {
  const { workspaceId } = useWorkspace()
  const [expanded, setExpanded] = useState<string | null>(null)
  const [showFile, setShowFile] = useState<{ patchId: string; idx: number } | null>(null)

  const patches = useQuery({
    queryKey: ['patches', workspaceId],
    queryFn:  () => api.get<{ data: Patch[] }>(`/api/v1/self/patches?workspace_id=${workspaceId}&limit=30`),
    refetchInterval: 15_000,
  })

  const rows = patches.data?.data ?? []
  return (
    <div className="p-6 space-y-4 max-w-7xl mx-auto">
      <div className="flex items-center gap-3">
        <Hammer className="w-5 h-5 text-sky-400" />
        <h1 className="text-xl font-semibold">Code Patches</h1>
        <span className="text-xs text-[var(--text-muted)] ml-1">{rows.length} · safety-gated · operator commits</span>
      </div>

      {rows.length === 0 ? (
        <div className="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-5 py-8 text-center text-sm text-[var(--text-muted)]">
          No patches yet. Click the hammer icon on a proposal to generate one.
        </div>
      ) : (
        <ul className="space-y-2">
          {rows.map(p => {
            const isOpen = expanded === p.id
            return (
              <li key={p.id} className="rounded-lg border border-[var(--border)] bg-[var(--surface)]">
                <div className="px-4 py-3 flex items-center gap-3">
                  <span className={`px-1.5 py-0.5 rounded text-[10px] border ${STATUS[p.status] ?? STATUS.pending}`}>{p.status}</span>
                  <span className="text-xs text-[var(--text-muted)] font-mono">{p.agent}</span>
                  <button onClick={() => setExpanded(isOpen ? null : p.id)} className="flex-1 text-left text-sm hover:underline">
                    {p.files.length} files · {p.tokensUsed > 0 ? `${p.tokensUsed} tokens · $${p.costUsdUsed.toFixed(4)}` : 'template mode'}
                  </button>
                  <span className="text-xs text-[var(--text-muted)] font-mono">{new Date(p.createdAt).toLocaleString().replace(',', '')}</span>
                </div>

                {isOpen && (
                  <div className="px-4 py-3 border-t border-[var(--border)] text-xs space-y-3">
                    {/* Safety report */}
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        {p.safetyReport.ok
                          ? <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                          : <ShieldAlert className="w-3.5 h-3.5 text-red-400" />}
                        <span className="font-medium">Safety policy: {p.safetyReport.ok ? 'PASS' : 'BLOCKED'}</span>
                      </div>
                      {!p.safetyReport.ok && p.safetyReport.blockedReasons && (
                        <ul className="text-[10px] text-red-300 font-mono ml-5 space-y-0.5">
                          {p.safetyReport.blockedReasons.map((r, i) => <li key={i}>• {r}</li>)}
                        </ul>
                      )}
                    </div>

                    {/* Sandbox report */}
                    <div>
                      <div className="font-medium mb-1">
                        Sandbox: {p.sandboxReport.ok ? <span className="text-emerald-400">PASS</span> : <span className="text-amber-400">FAILED/DEGRADED</span>}
                        {' '}· typecheck {p.sandboxReport.typecheck?.ran ? (p.sandboxReport.typecheck.passed ? '✓' : '✗') : '⊘'}
                      </div>
                      {p.sandboxReport.errors?.length > 0 && (
                        <ul className="text-[10px] text-amber-300 font-mono ml-5 space-y-0.5">
                          {p.sandboxReport.errors.map((e, i) => <li key={i}>• {e}</li>)}
                        </ul>
                      )}
                      {p.sandboxReport.typecheck?.output && !p.sandboxReport.typecheck.passed && (
                        <pre className="mt-1 ml-5 text-[10px] bg-[var(--bg)] border border-[var(--border)] rounded p-2 max-h-32 overflow-y-auto">{p.sandboxReport.typecheck.output.slice(0, 1000)}</pre>
                      )}
                    </div>

                    {/* Files */}
                    <div>
                      <div className="font-medium mb-1">Files ({p.files.length})</div>
                      <ul className="space-y-0.5">
                        {p.files.map((f, i) => (
                          <li key={i} className="flex items-center gap-2 text-[10px] font-mono">
                            <span className={f.op === 'create' ? 'text-emerald-400' : 'text-amber-400'}>{f.op === 'create' ? '+' : '~'}</span>
                            <button onClick={() => setShowFile(showFile?.patchId === p.id && showFile.idx === i ? null : { patchId: p.id, idx: i })}
                              className="hover:underline">
                              {f.path} <span className="text-[var(--text-muted)]">({f.contents.length} chars)</span>
                            </button>
                          </li>
                        ))}
                      </ul>
                      {showFile?.patchId === p.id && p.files[showFile.idx] && (
                        <pre className="mt-2 text-[10px] bg-[var(--bg)] border border-[var(--border)] rounded p-2 max-h-96 overflow-y-auto whitespace-pre-wrap">{p.files[showFile.idx]!.contents}</pre>
                      )}
                    </div>

                    {p.status === 'validated' && (
                      <div className="text-[10px] text-emerald-300 bg-emerald-500/10 border border-emerald-500/30 rounded p-2">
                        Patch validated. Review the file contents above, then manually commit via git.
                        After commit: POST /api/v1/self/proposals/{p.proposalId}/shipped with the commit SHA to close the loop.
                      </div>
                    )}
                  </div>
                )}
              </li>
            )
          })}
        </ul>
      )}
    </div>
  )
}
